name: garden_plants
version: 0.0.3
description: garden_plants Polymer application that uses dartling for its model.
author: Your Name
homepage: http://ondart.me/
documentation:
dependencies:
  browser: any
  polymer: any
  dartling:
    git: https://github.com/dzenanr/dartling.git
  dartling_default_app:
    git: https://github.com/dzenanr/dartling_default_app.git
transformers:
- polymer:
    entry_points: web/garden_plants.html  